<?php
session_start();
include('Connection.php');
if(!isset($_SESSION['User_Name'])){
    header("Location: index.php");
}
// Table
$table = "SELECT * FROM trackingtbl";
$query = mysqli_query($con,$table);

// Log out  
if($_SESSION['User_Name'] && $_SESSION['User_Password'] && $_SESSION['Role']){
    $type = $_SESSION['Role'];
}else{
    header("location:index.php");
}
// Insert
if(isset($_POST['insert-document'])){
  $tr = $_POST['Tr'];
  $tot = $_POST['tot'];
  $pr = $_POST['Pr'];
  $off = $_POST['Officename'];
  $date = $_POST['dt'];
  $submitedby = $_POST['Submitedby'];

  $insertDoc = "INSERT INTO `trackingtbl`(`Trackingnum`, `Type_of_transmital`, `Person_Responsible`, `office`, `date`, `SubmitedBy`,`Accepted`,`Declined_tbl`)
   VALUES ('$tr','$tot','$pr','$off','$date','$submitedby','1','0')";
   $con->query($insertDoc);
  echo"<script>window.location = 'Main.php'</script>";
  echo date('m/d/y', strtotime($some_date));

   
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="Main.css">
    
    <title>Main</title>
</head>
<script>
  var time = new Date().getTime();
$(document.body).bind("mousemove keypress", function(e) {
    time = new Date().getTime();
});

function refresh() {
    if(new Date().getTime() - time >= 100000) 
        window.location.reload(true);
    else 
        setTimeout(refresh, 10000);
}
setTimeout(refresh, 10000);
</script>
<style>
   @media only screen and (max-width: 600px){
    .resize{
      width: 60%;
    }
   }
</style>
<!-- Auto paste The tracking number that generated by the system -->
<script>
function PasteTracking(){
  let TrackingNo = document.getElementById('myInput').value;
  document.getElementById('input2').value = TrackingNo;

}
</script>
<body>
    <!-- NAV -->
    <nav class="navbar navbar-expand-lg navbar-dark"  style="background-color: #41969e">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <img src="sdo3.png" alt="" style = "width:10%;">
  <div class="collapse navbar-collapse" id="navbarTogglerDemo03" style='margin-left:2%;'>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
    <li class="nav-item active">
    <a class="navbar-brand" href="Main.php">Home</a>
    </li>
    <li class="nav-item active">
      <a class="navbar-brand" href="Logs.php" >Logs</a>
      </li>
        <!-- <li class="nav-item">
         <a class="navbar-brand" href="#" style="color: white;"  class="btn btn-primary" data-toggle="modal" data-target="#ForRecieve">Recieve</a>
        </li> -->
        <?php
        if($type == 'ADMIN'){
          echo'<li class="nav-item">
          <a class="navbar-brand" href="Accounts.php" style="color: white; ">Accounts</a>
          </li>';
        }
        ?>

      <li class="nav-item active">
      <a class="navbar-brand" href=""  class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">User setting</a>
      </li>
      <li class="nav-item">
      <a class="navbar-brand" href="Logout.php" style="color: white; ">Log out</a>
      </li>
    </ul>
</nav><br>
<?php
// $Count="select count(Accepted) from trackingtbl where Accepted = 0;";
// $Items=mysqli_query($con,$Count);
// $ItemsRow=mysqli_fetch_array($Items);
// echo "<h4>$ItemsRow[0]</h4>";  
?>
<script>
  function Copy() {
  // Get the text field
  var copyText = document.getElementById("myInput");

  // Select the text field
  copyText.select();
  copyText.setSelectionRange(0, 99999); // For mobile devices

   // Copy the text inside the text field
  navigator.clipboard.writeText(copyText.value);

  // Alert the copied text
  alert("Copied the text: " + copyText.value);
  event.preventDefault();
}
</script>
<label for=""></label>
<form action="" method='Post' style='width:30%; margin:auto;' >
<div class="form-group mx-sm-3 mb-2 " style='' >

      <?php
      if($type == 'GUEST'){
        echo'<h4>You are in a guest mode</h4>';

      }
      if($type == 'ADMIN' || $type =='USER'){
        echo '<button type="submit" style="float:left;" name="generate" class="btn btn-primary mb-2">Generate</button>';
      }
      ?>
      <!-- <button type="submit" style='float:left;' name='generate' class="btn btn-primary mb-2">Generate</button>
      <button style='float:right;' class="btn btn-secondary mb-2" onclick="Copy()">Copy</button> -->
      <input  id="myInput" type="text" readonly class="form-control" oninput='fucn(this.value)'  id='input1'  id="Typeoftransmit"  placeholder="Tracking number" value='<?php
   if(isset($_POST['generate'])){
      $date = date('mdy');
      echo $date, random_strings(3);}
    // echo $uniqId;
    function random_strings($length_of_string)
{
    // String of all alphanumeric character
    $str_result = rand(10,999999);
    // Shuffle the $str_result and returns substring
    // of specified length
    return substr(str_shuffle($str_result),
                       0, $length_of_string);
}
    ?>'>
   
  </form>
  </div>
<!-- Table For Sending and recieving Data -->
<table class="table table-striped table-active table-bordered" style='width:55%; margin:auto;max-height: 350px;overflow-y: scroll;'>
  <thead class="thead-dark">
  <th  style='text-align:center; width:15%;' colspan='5'><h4>Document Tracking System</h4></th>
    <tr>
      <th  style='text-align:center;'>On Process</th>
      <th style='text-align:center;'>Recieved</th>
      <th style='text-align:center;'>Declined</th>
      <?php
      if($type == 'GUEST'){

      }
      else{
        echo'      
        <th style="text-align:center; width:6%;">Send</th>
        <th style="text-align:center; width:6%;">Recieve</th>';
      }
      ?>

    </tr>
  </thead>
  <tbody>
    <?php 
    // Display How many onprocess,Recieve and declined
    $Count="select count(Accepted) from trackingtbl where Accepted = 0;";
    $Items=mysqli_query($con,$Count);
    $ItemsRow=mysqli_fetch_array($Items);

    $Count1="select count(Accepted) from trackingtbl where Accepted = 1;";
    $Items1=mysqli_query($con,$Count1);
    $ItemsRow1=mysqli_fetch_array($Items1);

    $Count2="select count(Accepted) from trackingtbl where Declined_tbl =  2;";
    $Items2=mysqli_query($con,$Count2);
    $ItemsRow2=mysqli_fetch_array($Items2);
    echo"<tr>
    <td style='text-align:center;'><h4>$ItemsRow1[0]</h4></td>
    <td style='text-align:center;'><h4>$ItemsRow[0]</h4></td>
    <td style='text-align:center;'><h4>$ItemsRow2[0]</h4></td>";
    if($type == 'GUEST'){

    }
    else{
      echo"    <td style='text-align:center;' class='upbtn'><a href=''class='btn btn-primary' data-toggle='modal' data-target='#ForSendingData' onfocus='myFunction()' oncliCk='PasteTracking()'>Send</a></td>
      <td style='text-align:center;' class='upbtn'><a href='#' style='color: white;'  class='btn btn-success' data-toggle='modal' data-target='#ForRecieve'>Recieve</a></td>
          </tr>";
    }


    ?>
  </tbody>
<style>
  @media only screen and (max-width: 600px){
   .tableFlex{
    overflow-y: scroll;
   }
  }
</style>
</table><br><br><hr>

<div class='tableFlex' style='width:100%;'>

<h4 style='text-align:center;'>Declined Transmitals</h4>

</table>
<table class="table table-striped table-active table-bordered" style='margin:auto;' id='itemTable'>
  <thead class="thead-dark">
    <tr>
      <th  style='text-align:center; width:15%;'>Tracking number</th>
      <th style='text-align:center; width:25%;'>Submited By</th>
      <th style='text-align:center; width:13%;'>Date of Declined</th>
      <th style='text-align:center; width:15%;'>Declined By</th>
      <th style='text-align:center; '>Reason</th>
      <th style='text-align:center; width:6%;'>Resend</th>
    </tr>
  </thead>
  <tbody>
    <?php
    $DeclinedData = "SELECT * FROM `trackingtbl` WHERE `Declined_tbl` = 2";
    $ShowDcData = mysqli_query($con,$DeclinedData);
    $num=mysqli_num_rows($ShowDcData);
    if ($num>0) {
       while ($result = mysqli_fetch_assoc($ShowDcData)) {
    echo"<tr>
    <td>".$result['Trackingnum']."</td>
    <td>".$result['SubmitedBy']."</td>
    <td>".$result['Date_of_declined']."</td>
    <td>".$result['Declinedby_tbl']."</td>
    <td>".$result['Reason']."</td>
    <td style='text-align:center;' class='upbtn'><a href='Resend.php?id=".$result['Trackingnum']."' style='color: white;'  class='btn btn-success'>Resend</a></td>
        </tr>";
        
      }}
    ?>
  </tbody>
</table></div>
<!-- Input fields -->
<!-- <div class="con">
<form class="form-inline"  method='POST'; style='margin:auto; width:30%; background-color: #51bec7; padding:30px; border-radius:5px;'>
  <div class="form-group mx-sm-3 mb-2 ">
    <input type="text" class="form-control" name='Tr'  id="Typeoftransmit"  placeholder="Tracking number" value='<?php
    // if(isset($_POST['generate'])){
    // echo $RandomNum = rand(100000000,999999999);}?>'>
  </div>
  <button type="submit" name='generate' class="btn btn-primary mb-2">Generate</button>
  <div class="form-group mx-sm-3 mb-2">
    <input type="text" class="form-control" name='tot' id="Typeoftransmit"  placeholder="type of transmital">
  </div>
  <div class="form-group mx-sm-3 mb-2">
    <input type="text" class="form-control" name='Pr' id="Typeoftransmit"  placeholder="Person responsible">
  </div>
  <div class="form-group mx-sm-3 mb-2">
    <input type="text" class="form-control" name='Officename' id="Typeoftransmit"  placeholder="Office">
  </div>
  <div class="form-group mx-sm-3 mb-2">
    <input type="text" class="form-control resize" name=Submitedby id="Typeoftransmit"  placeholder="Submited by:">
  </div>
  <div class="form-group mx-sm-3 mb-2">
    <input type="date" class="form-control resize" name=dt id="Typeoftransmit"  placeholder="Date">
  </div>
  <button type="submit" name='insert-document' class="btn btn-primary mb-2" onclick=" activate()">Send</button>
</form></div> -->
<script>
function activate() {
var result = confirm("Do you Want to activate this account?")
if(result == false){
  event.preventDefault();
}
}
</script>
<!-- User Setting -->
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">User Setting</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <label for="">Name</label><br>
        <?php
        $id = $_SESSION['user_ID'];
        $select = "select * from accounts where id = '$id'";
        $query=mysqli_query($con,$select);
        
        $result = mysqli_fetch_assoc($query);
        echo'
        <span style="    font-weight: bold;" ">'.$result["UserName"].'</span><br>
        <div class="line1"></div><br>
        <label for="">Password</label><br>';

        echo'<span style="    font-weight: bold;" ">'.$result["Password"].'</span><br>
        
        <div class="line1"></div><br>';

        echo'<label for="">Position</label><br>
        <span style="    font-weight: bold;">'.$result["Role"].'</span><br>
        <div class="line1"></div><br>
        <br><br>'; ?>
        Reminder: You cant change your role and user name.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <a href="UserSetting.php" class="btn btn-primary">UPDATE</a>
      </div>
    </div>
  </div>
</div>

<!-- ACTIVATE CLICK -->
<script>
function activate() {
var result = confirm("Do you Want to Forward this Data?")
if(result == false){
  event.preventDefault();
}
}
function deactivate() {
var con = confirm("Do you Want to deactivate this account?")
if(con == false){
  event.preventDefault();
}

}
</script>
<!-- Modal for recieving -->
<!-- Modal -->
<div class="modal fade" id="ForRecieve" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Enter tracking number</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <div class="input-group mb-2">
        <div class="input-group-prepend">
          <div class="input-group-text">Tracking number</div>
        </div>
        <form action="Forwarded.php" method="POST">
        <input type="text" class="form-control" id="inlineFormInputGroup" name='Enter-tracknum'  placeholder="Enter tracking number">
      </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">FIND</button></form>
      </div>
    </div>
  </div>
</div>
<!-- Modal For Sending Data -->
<div class="modal fade" id="ForSendingData" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Send Data</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="" method='POST'>
        <div class="form-group mx-sm-3 mb-2">
      <label for="">Tracking number</label>
      <input type="text" class="form-control" name='Tr' readonly id="input2"  placeholder="Tracking Number" required>
    </div>        
    <div class="form-group mx-sm-3 mb-2">
      <label for="">Type of transmital</label> 
      <input type="text" class="form-control" name='tot' id="Typeoftransmit"  placeholder="type of transmital" required>
    </div>
    <div class="form-group mx-sm-3 mb-2">
    <label for="">Person responsible</label>
      <input type="text" class="form-control" name='Pr' id="Typeoftransmit"  placeholder="Person responsible" required>
    </div>
    <div class="form-group mx-sm-3 mb-2">
    <label for="">Office Name</label>
      <input type="text" class="form-control" name='Officename' id="Typeoftransmit"  placeholder="Office" required>
    </div>
    <?php 
            $id = $_SESSION['user_ID'];
            $select = "select * from accounts where id = '$id'";
            $query=mysqli_query($con,$select);
            
            $result = mysqli_fetch_assoc($query);
        echo '
        <div class="form-group mx-sm-3 mb-2">
        <label for="">Submited by:</label> 
          <input type="text" class="form-control resize" name=Submitedby id="Typeoftransmit" readonly  placeholder="Submited by:" value="'.$result["Fullname"].'">
        </div>
        ';
    ?>

    <div class="form-group mx-sm-3 mb-2">
    <label for="">Date</label>
      <input type="date" class="form-control resize" name=dt id="Typeoftransmit"  placeholder="Date" required>
    </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" name='insert-document' class="btn btn-primary" onclick=" activate()">Send</button></form>
      </div>
    </div>
  </div>
</div>

<!-- END -->
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.13.2/b-2.3.4/b-html5-2.3.4/datatables.min.css" />
        <script type="text/javascript" src="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.13.2/b-2.3.4/b-html5-2.3.4/datatables.min.js"></script>
        <script>
            $(document).ready(function() {
                $('#itemTable').DataTable({
                    "dom": 'Bfrtip',
                    buttons: [
                        'copyHtml5',
                        'csvHtml5'
                    ]

                })
            });
        </script>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<!-- END -->
<!-- Dt Table -->
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.13.2/b-2.3.4/b-html5-2.3.4/datatables.min.css" />
        <script type="text/javascript" src="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.13.2/b-2.3.4/b-html5-2.3.4/datatables.min.js"></script>
        <script>
            $(document).ready(function() {
                $('#itemTable').DataTable({
                    "dom": 'Bfrtip',
                    buttons: [
                        'copyHtml5',
                        'csvHtml5'
                    ]

                })
            });
        </script>
  </body>
</html>